version: '3.7'

services:
  php-fpm:
    build:
      context: ${PHPFPM_CONF_FOLDER}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    depends_on:
      - mysql
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html

  nginx:
    build:
      context: ${NGINX_CONF_FOLDER}
    depends_on:
      - php-fpm
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html
      - ${NGINX_CONF_FOLDER}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_FOLDER}/sites/:/etc/nginx/sites-available
      - ${NGINX_CONF_FOLDER}/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST_USER_ID: ${USER_ID}
      HOST_GROUP_ID: ${GROUP_ID}

  mysql:
    image: mysql:5.7
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    volumes:
      - mysql-data:/var/lib/mysql
      - ${MYSQL_SCRIPTS_FOLDER}:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

volumes:
  mysql-data: