version: '3.7'

services:
  php-fpm:
    build:
      context: ${PHPFPM_CONF_FOLDER}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    depends_on:
      - mysql
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html

  nginx:
    build:
      context: ${NGINX_CONF_FOLDER}
    depends_on:
      - php-fpm
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html
      - ${NGINX_CONF_FOLDER}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_FOLDER}/sites/:/etc/nginx/sites-available
      - ${NGINX_CONF_FOLDER}/conf.d/:/etc/nginx/conf.d
    ports:
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${APP_ADDRESS}`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    environment:
      HOST_USER_ID: ${USER_ID}
      HOST_GROUP_ID: ${GROUP_ID}

  mysql:
    image: mysql:5.7
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    volumes:
      - mysql-data:/var/lib/mysql
      - ${MYSQL_SCRIPTS_FOLDER}:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${APP_ADDRESS}.phpmyadmin`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    environment:
      PMA_HOST: mysql

  traefik:
    image: "traefik:v2.3"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mysql-data: