version: '3.7'

services:
  nginx:
    build:
      context: ${NGINX_CONF_FOLDER}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html
      - ${NGINX_CONF_FOLDER}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_FOLDER}/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST_USER_ID: ${USER_ID}
      HOST_GROUP_ID: ${GROUP_ID}