version: '3.7'

services:
  php-fpm:
    build:
      context: ${PHPFPM_CONF_FOLDER}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html

  nginx:
    build:
      context: ${NGINX_CONF_FOLDER}
    depends_on:
      - php-fpm
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html
      - ${NGINX_CONF_FOLDER}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_FOLDER}/sites/:/etc/nginx/sites-available
      - ${NGINX_CONF_FOLDER}/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST_USER_ID: ${USER_ID}
      HOST_GROUP_ID: ${GROUP_ID}